require_relative '../../node_modules/react-native-test-app/test_app'

workspace 'WebviewExample.xcworkspace'

options = {
  :bridgeless_enabled => false,
  # todo: read config from ci
  :fabric_enabled => false,
  :hermes_enabled => false,
}

use_test_app! options
